### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yssoe** [thetatool/tastyworks-rs#1]
Hello, I'm looking at the source where you place orders, just a quick question please, is it possible to place orders without having any confirmation? I would like to build on your repo to make an easy order tool, now the current TW interface has different confirmation steps and that's very annoying :-) Thanks!

**Comment by t-mw** [comment]
Hi, I haven’t added order placement to this unofficial api. Because of the risk of getting it wrong I’d rather wait and see whether there are endpoints that can be used in the official api, once it’s released.

**Comment by yssoe** [comment]
Thanks, they told me 3 years ago an official api will be released but it never happens, did something change? Thanks

**Comment by t-mw** [comment]
Back in June they announced through tastytrade that they would be starting a beta 'soon', but still no concrete dates. You can email tastyworks support to be added to a waitlist for access to the beta.

**Comment by yssoe** [comment]
@t-mw i'm on the list, thanks and they confrimed me it's coming next year :-)
