### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by yssoe** [thetatool/tastyworks-rs#2]
Hello, to use this, could you describe a bit in the READ.me how to get this going, how to setup the API_ENV_KEY etc? 

thanks!!

**Comment by t-mw** [comment]
Hi, I've reworked how the api token is passed in and added an example to the README. Let me know if this helps.
The [documentation](https://docs.rs/tastyworks/latest/tastyworks/) still isn't very complete, but the main functions exported by the api should be fairly self-explanatory.
