### ISSUE TITLE
QUESTION: Sorry for this nooby question about converting some results to a polars dataframe ...

### ISSUE THREAD

**Issue by gittesti** [thetatool/tastyworks-rs#7]
Hi,

I am a nooby in rust ... very interested in your awesome api for tastyworks :)

I just started to learn rust a couple weeks ago ... converted my python scripts based on TD-API to rust ... and hopefully using your API to get the live data.

Q: when I do a `tastyworks::market_metrics(&["AA".to_string(), "AMZN".to_string()], &context)` I get a nice Vec<Item> ... but how do I convert it into a polars dataframe/series ? (btw, I am not familiar with serde etc.)

Thanks in advance for any help you can provide.

**Comment by t-mw** [comment]
Hi,

I haven't used polars before, but once you have a Vec it should be possible to create a [Series](https://docs.rs/polars/latest/polars/series/struct.Series.html#creation) from it with something like:
```rust
let s = Series::new("series", &vec);
```
or
```rust
let s = Series::from_vec("series", vec);
```

Using the [macro](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#using-a-macro) to construct the dataframe might work as well:

```rust
let df = df!("series" => &vec);
```

You can build the Vecs you need from the market metric structs with something like:

```rust
let vec: Vec<_> = items.iter().map(|item| item.key).collect();
```

**Comment by gittesti** [comment]
Thanks for the update ... in the meantime I was able to extract all data into dataframes ... for further processing :) 

Now the only thing missing is the LIVE data ... did you get the dxfeed ever to work ?

**Comment by t-mw** [comment]
There is some basic support for live data:

```rust
let mut streamer = tastyworks::streamer::Client::new(&context).await?;
streamer.connect()?;

// add subscriptions as required: "Quote", "Greeks" and "Trade" are examples of subscription names
let symbols = vec!["SPY".to_string()];
streamer.add_subscription("Quote", &symbols)?;

// poll for data, call this periodically to receive updates
let subscription_data = streamer.poll_subscriptions()?;

if let Some(quote_data) = subscription_data.get("Quote") {
  for ((quote_symbol, bid), ask) in quote_data
      .iter_field("eventSymbol")
      .zip(quote_data.iter_field("bidPrice"))
      .zip(quote_data.iter_field("askPrice"))
  {
      let quote_symbol = if let Some(symbol) = quote_symbol.as_str() {
          symbol
      } else {
          continue;
      };

      let bid_price = if let Some(price) = bid.to_price() {
          price
      } else {
          continue;
      };

      let ask_price = if let Some(price) = ask.to_price() {
          price
      } else {
          continue;
      };

      // use data
  }
}
```

**Comment by gittesti** [comment]
Thanks :) will look into this ...
